name: DiscordChatBridge
authors:
  - JohnyMuffin
  - Owen2k6
version: 2.0.7
main: main.java.com.johnymuffin.beta.discordchatbridge.DiscordChatBridge
softdepend:
  - DiscordCore
  - DiscordAuthentication