name: DiscordChatBridge
authors:
  - JohnyMuffin
  - Owen2k6
version: ${project.version}
main: com.johnymuffin.beta.discordchatbridge.DiscordChatBridge
softdepend:
  - DiscordCore
  - DiscordAuthentication
  - RetroBridge
